Step: build-step-credential-initializer-cgm79:

{"level":"warn","ts":1554480062.650388,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/backport-container-name-fix\" is not a valid GitHub commit ID"}
{"level":"info","ts":1554480062.652827,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
Step: build-step-git-source-*****-pytorch2-master-zb2x9:

{"level":"warn","ts":1554480064.2204998,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/backport-container-name-fix\" is not a valid GitHub commit ID"}
{"level":"info","ts":1554480065.69175,"logger":"fallback-logger","caller":"git-init/main.go:99","msg":"Successfully cloned \"https://github.com/*****/pytorch2\" @ \"v0.0.2\" in path \"/workspace/source\""}
Step: build-step-place-tools:

Step: build-step-setup-**-git-credentials:

Generated Git credentials file /workspace/xdg_config/git/credentials
Step: build-step-setup-step3:

Already on 'master'
Step: build-step-setup-step4:

Step: build-step-setup-step5:

Generated Git credentials file /workspace/xdg_config/git/credentials
Step: build-step-build-step6:

Collecting flake8
  Downloading https://files.pythonhosted.org/packages/e9/76/b915bd28976068a9843bf836b789794aa4a8eb13338b23581005cd9177c0/flake8-3.7.7-py2.py3-none-any.whl (68kB)
Collecting entrypoints<0.4.0,>=0.3.0 (from flake8)
  Downloading https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl
Collecting pyflakes<2.2.0,>=2.1.0 (from flake8)
  Downloading https://files.pythonhosted.org/packages/84/f2/ed0ffb887f8138a8fe5a621b8c0bb9598bfb3989e029f6c6a85ee66628ee/pyflakes-2.1.1-py2.py3-none-any.whl (59kB)
Collecting functools32; python_version < "3.2" (from flake8)
  Downloading https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
Collecting configparser; python_version < "3.2" (from flake8)
  Downloading https://files.pythonhosted.org/packages/ba/05/6c96328e92e625fc31445d24d75a2c92ef9ba34fc5b037fe69693c362a0d/configparser-3.7.4-py2.py3-none-any.whl
Collecting typing; python_version < "3.5" (from flake8)
  Downloading https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
Collecting enum34; python_version < "3.4" (from flake8)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8)
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.6.0,>=2.5.0 (from flake8)
  Downloading https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl (51kB)
Installing collected packages: configparser, entrypoints, pyflakes, functools32, typing, enum34, mccabe, pycodestyle, flake8
  Running setup.py install for functools32: started
    Running setup.py install for functools32: finished with status 'done'
Successfully installed configparser-3.7.4 entrypoints-0.3 enum34-1.1.6 flake8-3.7.7 functools32-3.2.3.post2 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.1 typing-3.6.6
You are using pip version 8.1.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Step: build-step-build-step7:

Collecting pytest
  Downloading https://files.pythonhosted.org/packages/7e/16/83b2a35c427b838df9836c9e7e4ae6dfbcbdea643db44652f693b1c57d70/pytest-4.4.0-py2.py3-none-any.whl (223kB)
Collecting hypothesis
  Downloading https://files.pythonhosted.org/packages/d5/0e/23b7a4f22816327a7851d865d1d872c6691d27ede51ffdc3069a1322bbae/hypothesis-4.14.5-py2-none-any.whl (256kB)
Collecting funcsigs>=1.0; python_version < "3.0" (from pytest)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest)
  Downloading https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/site-packages (from pytest)
Collecting attrs>=17.4.0 (from pytest)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting pathlib2>=2.2.0; python_version < "3.6" (from pytest)
  Downloading https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest)
  Downloading https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/lib/python2.7/site-packages (from pytest)
Collecting pluggy>=0.9 (from pytest)
  Downloading https://files.pythonhosted.org/packages/84/e8/4ddac125b5a0e84ea6ffc93cfccf1e7ee1924e88f53c64e98227f0af2a5f/pluggy-0.9.0-py2.py3-none-any.whl
Collecting more-itertools<6.0.0,>=4.0.0; python_version <= "2.7" (from pytest)
  Downloading https://files.pythonhosted.org/packages/2f/9d/dcfe59e213093695f108508af1214cf9cd95cc5489e46877ec5cb56369e5/more_itertools-5.0.0-py2-none-any.whl (52kB)
Collecting enum34; python_version == "2.7" (from hypothesis)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2>=2.2.0; python_version < "3.6"->pytest)
  Downloading https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
Installing collected packages: funcsigs, atomicwrites, attrs, scandir, pathlib2, py, pluggy, more-itertools, pytest, enum34, hypothesis
  Running setup.py install for scandir: started
    Running setup.py install for scandir: finished with status 'done'
Successfully installed atomicwrites-1.3.0 attrs-19.1.0 enum34-1.1.6 funcsigs-1.0.2 hypothesis-4.14.5 more-itertools-5.0.0 pathlib2-2.3.3 pluggy-0.9.0 py-1.8.0 pytest-4.4.0 scandir-1.10.0
You are using pip version 8.1.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
============================= test session starts ==============================
platform linux2 -- Python 2.7.5, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/workspace/source/.hypothesis/examples')
rootdir: /workspace/source
plugins: hypothesis-4.14.5
collected 3 items

test/test_helloworld_hypothesis.py .                                     [ 33%]
test/test_helloworld_pytest.py .                                         [ 66%]
test/test_helloworld_unittest.py .                                       [100%]

=========================== 3 passed in 1.57 seconds ===========================
Step: build-step-build-step8:

[36mINFO[0m[0000] Downloading base image python:onbuild        
ERROR: logging before flag.Parse: E0405 16:01:32.332830      12 metadata.go:142] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
ERROR: logging before flag.Parse: E0405 16:01:32.337718      12 metadata.go:159] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
2019/04/05 16:01:32 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0001] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0001] Downloading base image python:onbuild        
2019/04/05 16:01:33 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Executing 3 build triggers                   
[36mINFO[0m[0002] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0002] Checking for cached layer 10.59.251.141:5000/f7025f56c0d365aaf595994dc4d93dabe400cc4bef33ad68c6456a99eb613558... 
2019/04/05 16:01:34 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] No cached layer found for cmd RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0002] Unpacking rootfs as cmd RUN pip install --no-cache-dir -r requirements.txt requires it. 
[36mINFO[0m[0022] Taking snapshot of full filesystem...        
[36mINFO[0m[0031] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0031] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0031] Taking snapshot of files...                  
[36mINFO[0m[0031] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0031] cmd: /bin/sh                                 
[36mINFO[0m[0031] args: [-c pip install --no-cache-dir -r requirements.txt] 
Collecting torch (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/31/ca/dd2c64f8ab5e7985c4af6e62da933849293906edcdb70dac679c93477733/torch-1.0.1.post2-cp36-cp36m-manylinux1_x86_64.whl (582.5MB)
Collecting torchvision==0.2.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ca/0d/f00b2885711e08bd71242ebe7b96561e6f6d01fdb4b9dcf4d37e2e13c5e1/torchvision-0.2.1-py2.py3-none-any.whl (54kB)
Collecting conda (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/74/4e/c533c3136427be62c38cc0e038cabf167bb54489c2ced2f6df903c456861/conda-4.3.16.tar.gz (299kB)
Collecting future (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
Collecting onnx (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/99/26/753bca1bc4e7e254d34da82f5b2e213ca9b32cbeb2d9e305fec4abcfebf7/onnx-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (6.9MB)
Collecting six (from torchvision==0.2.1->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pillow>=4.1.1 (from torchvision==0.2.1->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/d2/c2/f84b1e57416755e967236468dcfb0fad7fd911f707185efc4ba8834a1a94/Pillow-6.0.0-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
Collecting numpy (from torchvision==0.2.1->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
Collecting pycosat>=0.6.1 (from conda->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/c0/fd/e38d68774c0a345b0090d608a90f1fbf423970d812f7ec7aef9ac024e648/pycosat-0.6.3.zip (66kB)
Collecting requests>=2.12.4 (from conda->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
Collecting ruamel.yaml>=0.11.14 (from conda->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/78/3f/684946c85b129bba50f7bcc5a1b984375a9fae85881a21b12c102c3df5a5/ruamel.yaml-0.15.90-cp36-cp36m-manylinux1_x86_64.whl (652kB)
Collecting protobuf (from onnx->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/5a/aa/a858df367b464f5e9452e1c538aa47754d467023850c00b000287750fa77/protobuf-3.7.1-cp36-cp36m-manylinux1_x86_64.whl (1.2MB)
Collecting typing>=3.6.4 (from onnx->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting typing-extensions>=3.6.2.1 (from onnx->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/0f/62/c66e553258c37c33f9939abb2dd8d2481803d860ff68e635466f12aa7efa/typing_extensions-3.7.2-py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.12.4->conda->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.12.4->conda->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests>=2.12.4->conda->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
Collecting idna<2.9,>=2.5 (from requests>=2.12.4->conda->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from protobuf->onnx->-r requirements.txt (line 6)) (39.2.0)
Installing collected packages: torch, six, pillow, numpy, torchvision, pycosat, urllib3, chardet, certifi, idna, requests, ruamel.yaml, conda, future, protobuf, typing, typing-extensions, onnx
  Running setup.py install for pycosat: started
    Running setup.py install for pycosat: finished with status 'done'
  Running setup.py install for conda: started
    Running setup.py install for conda: finished with status 'done'
  Running setup.py install for future: started
    Running setup.py install for future: finished with status 'done'
Successfully installed certifi-2019.3.9 chardet-3.0.4 conda-4.3.16 future-0.17.1 idna-2.8 numpy-1.16.2 onnx-1.4.1 pillow-6.0.0 protobuf-3.7.1 pycosat-0.6.3 requests-2.21.0 ruamel.yaml-0.15.90 six-1.12.0 torch-1.0.1.post2 torchvision-0.2.1 typing-3.6.6 typing-extensions-3.7.2 urllib3-1.24.1
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[36mINFO[0m[0094] Taking snapshot of full filesystem...        
[36mINFO[0m[0136] Using files from context: [/workspace/source] 
[36mINFO[0m[0136] Pushing layer 10.59.251.141:5000/f7025f56c0d365aaf595994dc4d93dabe400cc4bef33ad68c6456a99eb613558 to cache now 
ERROR: logging before flag.Parse: E0405 16:03:48.554944      12 metadata.go:142] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
ERROR: logging before flag.Parse: E0405 16:03:48.560389      12 metadata.go:159] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
2019/04/05 16:03:48 pushed blob sha256:db7a09fcb3f678d0a6cf5913272b2f1d77c4e93d7eff0552e1afbc93631b1f29
[36mINFO[0m[0136] COPY . /usr/src/app                          
[36mINFO[0m[0136] Taking snapshot of files...                  
[36mINFO[0m[0136] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0136] COPY requirements.txt .                      
[36mINFO[0m[0136] Taking snapshot of files...                  
[36mINFO[0m[0136] ENV PORT 8080                                
[36mINFO[0m[0136] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0136] EXPOSE 8080                                  
[36mINFO[0m[0136] cmd: EXPOSE                                  
[36mINFO[0m[0136] Adding exposed port: 8080/tcp                
[36mINFO[0m[0136] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0136] ENTRYPOINT ["python"]                        
[36mINFO[0m[0136] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0136] CMD ["app.py"]                               
[36mINFO[0m[0136] No files changed in this command, skipping snapshotting. 
2019/04/05 16:05:09 pushed blob sha256:79685097451abd4d9efcdeaa42e1545f60c3f8283b6d2b9844ff936d919d7eae
2019/04/05 16:05:09 10.59.251.141:5000/f7025f56c0d365aaf595994dc4d93dabe400cc4bef33ad68c6456a99eb613558:latest: digest: sha256:3ee12cd6d7d423699d1c96225d480b776045148976aab3d722412c56063b572f size: 430
ERROR: logging before flag.Parse: E0405 16:05:09.657681      12 metadata.go:142] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
ERROR: logging before flag.Parse: E0405 16:05:09.662763      12 metadata.go:159] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
2019/04/05 16:05:09 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2019/04/05 16:05:09 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2019/04/05 16:05:09 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2019/04/05 16:05:09 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2019/04/05 16:05:09 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2019/04/05 16:05:09 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2019/04/05 16:05:09 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2019/04/05 16:05:09 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2019/04/05 16:05:09 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2019/04/05 16:05:09 pushed blob sha256:c652c9d3fdfbb3525a1cca32b8c3496d83c39b7537e998e60c1f41937452d03b
2019/04/05 16:05:09 pushed blob sha256:b93d719469ff1afd5ff317430fe00fb71d4f46546638f3b99c4a96284dd89a9e
2019/04/05 16:05:09 pushed blob sha256:61095f0940c6f36f6fe5e9caea189ec4d81be21ab6fc0f479060c21d58280f38
2019/04/05 16:05:09 pushed blob sha256:a5e9b6ec7f691ae47c27312320edb3ced3b886b0f07bad933ec805203d5e7b6f
2019/04/05 16:06:24 pushed blob sha256:79685097451abd4d9efcdeaa42e1545f60c3f8283b6d2b9844ff936d919d7eae
2019/04/05 16:06:24 10.59.251.141:5000/*****/pytorch2:0.0.2: digest: sha256:e604a19b09ff262e7cb92f334fb4f8ea07674dc84f6570af5371e3ece6b52a3a size: 2386
Step: build-step-build-step9:

no CVE provider running in the current ** namespace so skip adding image to be analysed
Step: build-step-promote-step10:

Converted /workspace/source/charts/pytorch2 to an unshallow repository
Generating change log from git ref f03c1ce51e082683343eea8ea70ed713a1366da0 => 37ddcb0bfc10af51936af6e468da2d4bc4827aef
Failed to enrich commits with issues: User.jenkins.io "-0" is invalid: metadata.name: Invalid value: "-0": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
Failed to enrich commits with issues: User.jenkins.io "-0" is invalid: metadata.name: Invalid value: "-0": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
Finding issues in commit messages using git format
No release found for *****/pytorch2 and tag v0.0.2 so creating a new release
Updated the release information at https://github.com/*****/pytorch2/releases/tag/v0.0.2
generated: /workspace/source/charts/pytorch2/templates/release.yaml
Created Release pytorch2-0-0-2 resource in namespace **
Updating PipelineActivity *****-pytorch2-master-2 with version 0.0.2
Updated PipelineActivities *****-pytorch2-master-2 with release notes URL: https://github.com/*****/pytorch2/releases/tag/v0.0.2
Step: build-step-promote-step11:

No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: releases http://jenkins-x-chartmuseum:8080
Successfully added Helm repository releases.
Adding missing Helm repo: jenkins-x http://chartmuseum.jenkins-x.io
Successfully added Helm repository jenkins-x.
No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file pytorch2-0.0.2.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}
Step: build-step-promote-step12:

prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
Promoting app pytorch2 version 0.0.2 to namespace **-staging
Created Pull Request: https://github.com/*****/environment-d29-staging/pull/27

Pull Request https://github.com/*****/environment-d29-staging/pull/27 is merged at sha 00b27693504586b3f48dfa2b7d24df281a23a365
Pull Request merged but we are not waiting for the update pipeline to complete!
